### ISSUE TITLE
Switch/Edit Characteristics (Optional Rule)

### ISSUE THREAD

**Issue by thekeeperofarcanelore** [Miskatonic-Investigative-Society/call-of-cthulhu-foundryvtt-investigator-wizard#1]
Hi there! Thank you for the Investigator Creation Wizard!

Will there be a way to switch/edit the characteristics that you have rolled while still in the Investigator Creation Wizard? The only characteristic value that can be edited is Luck. I'm referring to the Optional Rule for Creating Investigator - Option 3: Choosing Where to Place Rolled Characteristics. I was hoping we could switch the characteristic values around after rolling them in the wizard.

**Comment by snap01** [comment]
This module only contains compendium data which is used by the CoC7 system Investigator Wizard.

The optional rule will be added to the next release of the CoC7 system.
